intlify/eslint-plugin-vue-i18n

lib/utils/index.js, tests/lib/rules/no-missing-keys.js
Currently the plugin crashes if a nested path does not exist
Not sure why did it output double the error vs non-nested path though
=> :bug: Fix plugin crashes on missing nested path

docs/rules/no-raw-text.md, docs/rules/no-unused-keys.md, lib/rules/no-raw-text.js, tests/lib/rules/no-raw-text.js
Allows node, pattern and text based ignores on the no-raw-text rule
```
'vue-i18n/no-raw-text': ['warn', {
ignoreNodes: ['md-icon', 'v-icon'],
ignorePattern: '^[-#:()&]+$',
ignoreText: ['EUR', 'HKD', 'USD'],
}]
```
https://github.com/kazupon/eslint-plugin-vue-i18n/issues/27
=> No raw text ignore nodes/pattern/text

lib/rules/no-raw-text.js, tests/lib/rules/no-raw-text.js
Tests directive value against `ignorePattern` and `ignoreText` before emitting. Fixes #58
=> fix: check directive value; refactor directive visitor; test

docs/rules/no-raw-text.md
This PR replace `$t()` instead of `$()`
=> docs: fix $t in example

.vscode/settings.json, lib/utils/collect-keys.js, tests/fixtures/no-unused-keys/valid/vue-cli-format/locales/en.json, tests/fixtures/no-unused-keys/valid/vue-cli-format/locales/ja.json, tests/fixtures/no-unused-keys/valid/vue-cli-format/src/App.vue, tests/lib/rules/no-unused-keys.js
fixes #90 
This PR also supports the `<i18n-t>` component.
refs #91, #93
=> Fix false positives of key used in `<i18n>` component in `no-unused-keys` rule.

lib/rules/no-dynamic-keys.js, lib/rules/no-missing-keys.js, tests/lib/rules/no-dynamic-keys.js, tests/lib/rules/no-missing-keys.js
=> Change `no-missing-keys` and `no-dynamic-keys` rules to also verify keys used in the `<i18n-t>` component.

package.json, ship.config.js
It seems that the build runs by default when the buildCommand option is removed.
https://community.algolia.com/shipjs/reference/all-config.html#buildcommand
ref #99
=> Change to use buildCommand option of shipjs.

docs/started.md, lib/utils/collect-keys.ts, package.json, tests/fixtures/no-unused-keys/invalid/typescript/.eslintrc.js, tests/fixtures/no-unused-keys/invalid/typescript/locales/en.json, tests/fixtures/no-unused-keys/invalid/typescript/locales/ja.yaml, tests/fixtures/no-unused-keys/invalid/typescript/src/App.vue, tests/fixtures/no-unused-keys/invalid/typescript/src/main.ts, tests/lib/rules/no-unused-keys.ts
I've found that using `parserOptions.parser` overwrites the `.json` and `.yaml` parsers and doesn't work correctly.
I added a workaround to the document to work around this issue and added a test case to make sure this works correctly.
refs #103
=> Add TypeScript test case and add TypeScript FAQ to doc.

lib/utils/parsers/index.ts, tests/lib/rules/no-unused-keys.ts
=> Fix false negatives in `<i18n>` block without `<template>` in `no-unused-keys` rule.

tests/lib/rules/no-html-messages.ts, tests/lib/rules/no-unused-keys.ts
This PR refactors test cases that uses CLIEngine to changes it to use testOnFixtures.
=> Refactor test cases that use CLIEngine.

lib/rules/no-duplicate-keys-in-locale.ts, lib/rules/no-unused-keys.ts, tests/lib/rules/no-duplicate-keys-in-locale.ts, tests/lib/rules/no-unused-keys.ts
This PR fixes false positives when the key contains objects, like in the following YAML.
```yaml
? {foo: bar}
: value
```
=> Fix false positives when key contains object in YAML in `no-unused-keys` and `no-duplicate-keys-in-locale` rules.

lib/configs/base.ts, lib/rules/no-duplicate-keys-in-locale.ts, lib/rules/no-html-messages.ts, lib/rules/no-unused-keys.ts, lib/types/eslint.ts, lib/utils/locale-messages.ts, lib/utils/parsers/index.ts, package.json, tests-integrations/config-recommended/.eslintrc.js, tests-integrations/config-recommended/yarn.lock, yarn.lock
This PR replaces the JSON parser from eslint-plugin-jsonc to jsonc-eslint-parser.
Previously, eslint-plugin-jsonc had both the ESLint plugin module and the JSON parser module, but now the parser is separated as the jsonc-eslint-parser package.
With this change, it will not be affected by the version upgrade that updated only the rules of eslint-plugin-jsonc.
=> Replace from eslint-plugin-jsonc to jsonc-eslint-parser.

README.md, docs/started.md
This PR is fix typo in document and dead link in `README.md`
=> docs: Fix typo and dead link

.eslintrc.js, lib/types/eslint.ts, lib/types/nodes.ts, lib/types/vue-parser-services.ts, lib/utils/cache-function.ts, lib/utils/glob-sync.ts, lib/utils/ignored-paths.ts, scripts/update-docs-index.ts, tests/lib/rules/key-format-style.ts, tests/lib/test-utils.ts
This PR modifies the eslint configuration so that this project uses the `@typescript-eslint/consistent-type-imports` rule.
=> Chores: Update eslint config

.eslintrc.js, docs/started.md, lib/rules/no-unused-keys.ts, lib/types/eslint.ts, lib/utils/collect-linked-keys.ts, lib/utils/message-compiler/parser-v8.ts, lib/utils/message-compiler/parser.ts, lib/utils/message-compiler/traverser.ts, lib/utils/message-compiler/utils.ts, package.json, tests/lib/utils/collect-linked-keys.ts, tests/lib/utils/message-compiler/parser-v8-data.ts, tests/lib/utils/message-compiler/parser-v8.ts, tests/lib/utils/message-compiler/utils.ts, yarn.lock
This PR uses `@intlify/message-compiler` and supports vue-i18n v9 message format. e.g. `@:{'string'}`
=> Use `@intlify/message-compiler` and supports vue-i18n v9 message format

docs/rules/README.md, docs/rules/no-deprecated-i18n-component.md, lib/rules.ts, lib/rules/no-deprecated-i18n-component.ts, scripts/update-docs-index.ts, scripts/update-rule-docs.ts, tests/lib/rules/no-deprecated-i18n-component.ts
This PR adds `@intlify/vue-i18n/no-deprecated-i18n-component` rule that reports use of deprecated `<i18n>` components (in Vue I18n 9.0.0+).
refs #161 
In #161, the name of the rule was proposed as `no-deprecated-translation-component-name`, but if `<i18n-t>` is deprecated in v10+, it will be difficult to think of a rule with a new name, so the rule I renamed it to `no-deprecated-i18n-component`.
=> Add no-deprecated-i18n-component rule

docs/rules/README.md, docs/rules/no-deprecated-i18n-place-attr.md, lib/rules.ts, lib/rules/no-deprecated-i18n-place-attr.ts, lib/utils/index.ts, tests/lib/rules/no-deprecated-i18n-place-attr.ts
This PR adds `@intlify/vue-i18n/no-deprecated-i18n-place-attr` rule that reports use of deprecated `place` attribute (Removed in Vue I18n 9.0.0+).
refs #161
=> Add no-deprecated-i18n-place-attr rule

docs/rules/README.md, docs/rules/no-i18n-t-path-prop.md, lib/rules.ts, lib/rules/no-i18n-t-path-prop.ts, lib/utils/index.ts, tests/lib/rules/no-i18n-t-path-prop.ts
This PR adds `@intlify/vue-i18n/no-i18n-t-path-prop` rule that reports use of `path` prop with `<i18n-t>` component.
refs #161
=> Add no-i18n-t-path-prop rule

docs/rules/README.md, docs/rules/no-deprecated-i18n-places-prop.md, lib/rules.ts, lib/rules/no-deprecated-i18n-places-prop.ts, lib/utils/index.ts, tests/lib/rules/no-deprecated-i18n-places-prop.ts
This PR adds `@intlify/vue-i18n/no-deprecated-i18n-places-prop` rule that reports use of deprecated `places` prop (Removed in Vue I18n 9.0.0+).
refs #161
=> Add no-deprecated-i18n-places-prop rule

package.json
And another fix for usage with yarn 2 :see_no_evil: 
```
Error: Failed to load plugin '@intlify/vue-i18n' declared in '.eslintrc.js': @intlify/eslint-plugin-vue-i18n tried to access debug, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: debug (via "debug")
Required by: @intlify/eslint-plugin-vue-i18n@virtual:4ad93fa146a4e0d5ddd4599ecd9d82ecb03b424b9240d3d1508d839a1bff9fac247ecac5d150c68fb68844d9d337327ae2ac370f3cd8a72ffa073d59a537b0db#npm:0.11.0 (via ./.yarn/$$virtual/@intlify-eslint-plugin-vue-i18n-virtual-940b1fb35b/0/cache/@intlify-eslint-plugin-vue-i18n-npm-0.11.0-b29cdc793c-290af4444f.zip/node_modules/@intlify/eslint-plugin-vue-i18n/dist/rules/)
```
=> fix: add debug as dependency

lib/rules/no-raw-text.ts, lib/utils/index.ts, tests/lib/rules/no-raw-text.ts
=> Fix false positives for non component template in `no-raw-text` rule.

lib/rules/no-missing-keys.ts, tests/lib/rules/no-missing-keys.ts
refs #251 
---
This will increase the warning and should be released in a minor version.
=> Fix false negatives for `<i18n-t keypath>` in `no-missing-key` rule

lib/rules/key-format-style.ts, lib/utils/casing.ts, tests/lib/rules/key-format-style.ts
=> Add `SCREAMING_SNAKE_CASE` option to `key-format-style` rule

lib/rules/no-unused-keys.ts, lib/utils/locale-messages.ts, tests/lib/rules/no-missing-keys.ts, tests/lib/rules/no-unused-keys.ts
=> Fix bug when using delimited-like path.

docs/rules/no-unused-keys.md, lib/rules/no-raw-text.ts, lib/rules/no-unused-keys.ts, lib/utils/regexp.ts, tests/lib/rules/no-unused-keys.ts
=> Add ignores option to no-unused-keys rule

lib/rules/no-missing-keys.ts, lib/utils/index.ts, tests/lib/rules/no-missing-keys.ts
=> Fix false negatives when using parsers other than vue-eslint-parser in no-missing-keys

lib/rules/no-duplicate-keys-in-locale.ts, lib/rules/no-raw-text.ts, lib/types/i18n.ts, lib/utils/locale-messages.ts, tests/lib/rules/no-duplicate-keys-in-locale.ts, tests/lib/rules/no-raw-text.ts
=> Fix crash with null value in no-raw-text rule

package.json, pnpm-lock.yaml
Please change this PR's base branch to a newly created `beta` branch :raised_hands: 
To resolve https://github.com/nuxt-modules/i18n/issues/2098
=> feat(deps): update @intlify dependencies to v9.3.0-beta.19

.changeset/forty-tools-dream.md, lib/utils/key-path.ts, tests/lib/rules/no-missing-keys.ts
(as noted in https://github.com/intlify/eslint-plugin-vue-i18n/issues/260#issuecomment-1618963764)
For a translation key like `$t('missing.')` the parse function from core utilities returns undefined.
Previously this was turned into an empty array which caused all of those paths to be false positives.
If the given key can't be parsed as "path" properly, the correct handling is to treat it as a single item path with the provided string as the only item.
This also revealed another faulty test, where `keypath="'hello'"` was passing even though it should not.
=> fix: no-missing-keys rule reports false positive with trailing dot

.changeset/config.json, .changeset/smart-bugs-study.md
The repository does not have a `main` branch as of now.
Alternatively, the repository's main branch can be renamed of course.
=> chore(changeset): set base branch to `master`

.changeset/gentle-months-protect.md, .github/workflows/test.yml
Just making it a little more clear what the jobs are there for.
=> ci(test): reformat job names

.changeset/khaki-eyes-serve.md, lib/utils/collect-keys.ts, tests/lib/rules/no-unused-keys.ts
fix: https://github.com/intlify/eslint-plugin-vue-i18n/issues/447
=> fix: adds I18nT keyword into key collection

.changeset/modern-apricots-flash.md, docs/rules/key-format-style.md, lib/rules/key-format-style.ts, lib/utils/casing.ts, tests/lib/rules/key-format-style.ts
Our company-wide translation key policy calls for all lowercase keys. I opened an [issue](https://github.com/intlify/eslint-plugin-vue-i18n/issues/431) a while ago but never got any answers. Here’s my PR.
=> feat: add `lowercase` to `key-format-style` rule

docs/.vitepress/config.mts
I was trying to look something up in the docs and noticed that local search was not enabled in VitePress. It looks like this:
---
Note: [CONTRIBUTING.md](https://github.com/intlify/eslint-plugin-vue-i18n/blob/281a248f4800e8f8ba84da80c7fded592e379104/.github/CONTRIBUTING.md#pull-request-guidelines) suggests submitting PRs to `dev`, but that branch does not seem to exist.
=> docs: enable local search

.changeset/new-apples-ring.md, docs/rules/index.md, docs/rules/no-deprecated-tc.md, lib/index.ts, lib/rules/no-deprecated-tc.ts, tests/lib/rules/no-deprecated-tc.ts
In vue-i18n v10, `tc` and `$tc` are going to deprecated.
vue-i18n has already published docs for breaking changes.
https://vue-i18n.intlify.dev/guide/migration/breaking10.html#deprecate-tc-and-tc-for-legacy-api-mode
This rule supports migration.
=> feat: add `no-deprecated-tc` rule

.changeset/red-bulldogs-accept.md, docs/rules/index.md, docs/rules/no-deprecated-tc.md, lib/configs/flat/recommended.ts, lib/configs/recommended.ts, lib/rules/no-deprecated-tc.ts
I made the mistake for my categorizing... 😓 
I've just categorized it correctly.
=> fix: `no-deprecated-tc` rule wrong category

.changeset/gorgeous-snails-knock.md, .github/workflows/Release.yml, .github/workflows/test.yml, docs/started.md, package.json
=> breaking: drop support for versions less than node v18

.changeset/slow-needles-smash.md, .github/workflows/Release.yml, .github/workflows/test.yml, docs/started.md, package.json
=> breaking: drop support for versions less than eslint v8

.changeset/light-cows-wonder.md, docs/rules/index.md, docs/rules/no-deprecated-i18n-component.md, docs/rules/no-deprecated-i18n-place-attr.md, docs/rules/no-deprecated-i18n-places-prop.md, docs/rules/no-deprecated-modulo-syntax.md, docs/rules/no-i18n-t-path-prop.md, docs/rules/valid-message-syntax.md, lib/configs/flat/recommended.ts, lib/configs/recommended.ts, lib/rules/no-deprecated-i18n-component.ts, lib/rules/no-deprecated-i18n-place-attr.ts, lib/rules/no-deprecated-i18n-places-prop.ts, lib/rules/no-deprecated-modulo-syntax.ts, lib/rules/no-i18n-t-path-prop.ts, lib/rules/valid-message-syntax.ts
This PR changes the recommended config. All rules that belong to `category: 'Recommended'` are now enabled.
Please let me know if there are any other rules you think should be enabled.
---
Related to #512
close #275
=> feat!: update recommended config

docs/started.md
The flat config was referenced in the section about configuring the `.eslintrc.*` file type.
=> docs: remove unnecessary text from old config

.changeset/rotten-kangaroos-hope.md, tsconfig.json
Currently the `target` in the `tsconfig.json` file it set to ES2015, which means that the TypeScript compiler is polyfilling the `await` keyword in `lib/utils/parser-config-resolver/worker.ts` because it is an ES2017 language feature.
To avoid that happening this pull request bumps the target in the `tsconfig.json` file to ES2017. This is a non-breaking change as this package dropped Node.js versions older than 18 in version 3.0.0 and Node.js 18 supports ES2022 language features.
Before and after diff of `dist/utils/parser-config-resolver/worker.js`:
```diff
@@ -1,21 +1,12 @@
"use strict";
-var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
-    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); …
```
=> fix: Bump tsconfig target to es2017 to avoid polyfilling await

.changeset/chilled-colts-destroy.md, docs/rules/index.md, docs/rules/no-deprecated-v-t.md, lib/configs/flat/recommended.ts, lib/configs/recommended.ts, lib/index.ts, lib/rules/no-deprecated-v-t.ts, tests/lib/rules/no-deprecated-v-t.ts
In vue-i18n v11, `v-t` custom directive is going to deprecated.
vue-i18n has already published docs for breaking changes.
https://vue-i18n.intlify.dev/guide/migration/breaking11.html#deprecate-custom-directive-v-t
This rule supports migration.
=> feat: add `no-deprecated-v-t` rule

.changeset/seven-boxes-call.md, docs/started.md, lib/index.ts, scripts/update-index.ts, tests/integrations/flat-config/eslint.config.js, tests/integrations/legacy-config/.eslintrc.cjs
This PR renames the flat configs to `recommended` and the legacy configs to `recommended-legacy`.
`flat/recommended` will remain for backward compatibility.
=> feat!: rename configs

docs/started.md
=> docs: fix "module.export" wrong spells

.changeset/fast-brooms-bake.md, package.json, pnpm-lock.yaml, tsconfig.build.json
=> feat(types): add TypeScript definitions

.changeset/dry-chefs-battle.md, lib/utils/parser-config-resolver/should-use-flat-config.ts
Add Typescript config filenames to the lookup list (fix `@intlify/vue-i18n/no-unused-keys ` not working with Typescript-based configs)
=> Add Typescript config files to supported filename list

.changeset/unlucky-grapes-tie.md, lib/rules/no-raw-text.ts
[no-raw-text](https://github.com/intlify/eslint-plugin-vue-i18n/blob/b2f2e9ca24a3ebffc0ea76df40d8924aed70002e/lib/rules/no-raw-text.ts#L819) rule currently allows extra properties to be passed in options object, which should not be allowed. This makes it easier for typos in rule options to go unnoticed.
This PR simply disallows extra properties in this rule's schema.
=> fix: disallow extra properties in rule options

.changeset/empty-steaks-stare.md, lib/rules/no-dynamic-keys.ts
The `no-dynamic-keys` rule isn't being triggered for `.js` and `.ts` files when used with the `@vue/eslint-config-typescript` plugin. You can find a repository with a reproduction of this issue at https://github.com/mcler/no-dynamic-keys-reproduce
Modified the rule implementation by adding a `compositingVisitors` function wrapper, following the approach used in the `no-missing-keys` rule.
=> Fix not triggering rule no-dynamic-keys in non-vue files

docs/started.md
This PR adds a note to clarify that JavaScript-based locale files (`.js` and `.ts`) are not currently supported, with a reference to the relevant GitHub issue.
This helps users understand the current limitations of the plugin and provides a link to track the feature request.
Thank you. #32
=> docs: add note about JavaScript-based locale files not being supported
